---
- hosts: all
  roles:
    - workstation
  vars_prompt:
    - name: user_to_add
      prompt: "Which domain user may i add to local groups"
      private: no
    - name: domain_user
      prompt: "enter your domain user name"
      private: no
    - name: domain_pass
      prompt: "enter pass of your domain user"
      private: yes
