---
# tasks file for workstation
- name: stop unattended-upgrades
  systemd:
    name: unattended-upgrades
    state: stopped

- name: update packages
  apt:
    update_cache: yes
    install_recommends: yes
    only_upgrade: yes
    upgrade: dist

- name: install new user's packages
  apt:
    name: "{{item}}"
  with_items: "{{packages.users}}"

- name: install domain's packages
  apt:
    name: "{{item}}"
  with_items: "{{packages.ad}}"

- name: set hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    restart systemd-logind

- name: copy head file
  template:
    src: head.j2
    dest: /etc/resolvconf/resolv.conf.d/head
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: set hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: set ntp configuration
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    restart ntp
