---
# tasks file for workstation
- name: stop apt-daily.service
  systemd:
    name: apt-daily.service
    state: stopped

- name: stop apt-daily.timer
  systemd:
    name: apt-daily.timer
    state: stopped

- name: stop apt-daily-upgrade.service
  systemd:
    name: apt-daily-upgrade.service
    state: stopped

- name: stop apt-daily-upgrade.timer
  systemd:
    name: apt-daily-upgrade.timer
    state: stopped

- name: stop unattended-upgrades
  systemd:
    name: unattended-upgrades
    state: stopped

- name: update packages
  apt:
    update_cache: yes
    install_recommends: yes
    only_upgrade: yes
    upgrade: dist
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 20

- name: install new user's packages
  apt:
    name: "{{item}}"
  with_items: "{{packages.users}}"

- name: install domain's packages
  apt:
    name: "{{item}}"
  with_items: "{{packages.ad}}"


- name: set hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: set hostname
  hostname:
    name: "{{host_name}}"

- name: create resolv.conf.d directory
  file:
    path: /etc/resolvconf/resolv.conf.d
    owner: root
    group: root
    mode: 0755
    state: directory


- name: copy head file
  template:
    src: head.j2
    dest: /etc/resolvconf/resolv.conf.d/head
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    restart networking

- name: set ntp configuration
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    restart ntp

- name: set kerberos configuration
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: set samba configuration
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: set limits
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: set nsswitch
  template:
    src: nsswitch.conf.j2
    dest: /etc/nsswitch.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: set pamd common-session config
  template:
    src: common-session.j2
    dest: /etc/pam.d/common-session
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: restart samba
  systemd:
    name: smbd
    state: restarted

- name: connect to domain
  command: /usr/bin/net ads join -U "{{domain_user}}"%"{{domain_pass}}"
  register: join

- name: check "/usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf"
  stat:
    path: /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf
  register: ldm_config_exist
  when: join is success

- name: add parameters to "/usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf"
  template:
    src: 50-ubuntu.conf.j2
    dest: /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  when: ldm_config_exist.stat.exists

- name: restart winbind
  systemd:
    name: winbind
    state: restarted

- name: Reboot immediately if there was a change.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 20
    delay: 20
    timeout: 300

- name: wait for domain conection establishing
  shell: wbinfo -u
  register: wbinfo_status
  until: wbinfo_status is success
  delay: 5
  retries: 12

- name: add domain user to local groups
  shell: adduser "{{user_to_add}}" "{{item}}"
  with_items: "{{local_groups}}"
  when: join is succeeded